from __future__ import annotations

import os
from abc import ABC, abstractmethod

import httpx

from core.config import get_llm_settings


class LLMClient(ABC):
    @abstractmethod
    def generate(
        self,
        prompt: str,
        *,
        temperature: float = 0.2,
        json_mode: bool = False,
    ) -> str:
        """Return the raw text generated by the configured model."""


class GeminiLLMClient(LLMClient):
    def __init__(self, *, api_key: str, model: str) -> None:
        if not api_key:
            raise ValueError("GEMINI_API_KEY is not set")

        try:
            import google.generativeai as genai
        except ImportError as exc:
            raise RuntimeError("google-generativeai is required for the Gemini provider") from exc

        os.environ.pop("GOOGLE_API_KEY", None)
        os.environ["GOOGLE_API_KEY"] = api_key
        genai.configure(api_key=api_key)

        self._model = genai.GenerativeModel(model)

    def generate(
        self,
        prompt: str,
        *,
        temperature: float = 0.2,
        json_mode: bool = False,
    ) -> str:
        generation_config = {"temperature": temperature}
        if json_mode:
            generation_config["response_mime_type"] = "application/json"

        response = self._model.generate_content(
            prompt,
            generation_config=generation_config,
        )
        raw_text = getattr(response, "text", None)
        if not raw_text:
            raise RuntimeError("Gemini returned an empty response")
        return raw_text.strip()


class OllamaLLMClient(LLMClient):
    def __init__(self, *, base_url: str, model: str, timeout_seconds: float) -> None:
        if not base_url:
            raise ValueError("OLLAMA_BASE_URL is not set")
        if not model:
            raise ValueError("OLLAMA_MODEL is not set")

        self.base_url = base_url.rstrip("/")
        self.model = model
        self.timeout_seconds = timeout_seconds

    def generate(
        self,
        prompt: str,
        *,
        temperature: float = 0.2,
        json_mode: bool = False,
    ) -> str:
        payload = {
            "model": self.model,
            "prompt": prompt,
            "stream": False,
            "options": {"temperature": temperature},
        }
        if json_mode:
            payload["format"] = "json"

        response = httpx.post(
            f"{self.base_url}/api/generate",
            json=payload,
            timeout=self.timeout_seconds,
        )
        response.raise_for_status()

        data = response.json()
        raw_text = data.get("response")
        if not raw_text:
            raise RuntimeError("Ollama returned an empty response")
        return raw_text.strip()


_llm_client: LLMClient | None = None


def build_llm_client() -> LLMClient:
    settings = get_llm_settings()

    if settings.provider == "gemini":
        return GeminiLLMClient(
            api_key=settings.gemini_api_key,
            model=settings.gemini_model,
        )

    if settings.provider == "ollama":
        return OllamaLLMClient(
            base_url=settings.ollama_base_url,
            model=settings.ollama_model,
            timeout_seconds=settings.ollama_timeout_seconds,
        )

    raise ValueError(
        f"Unsupported LLM_PROVIDER '{settings.provider}'. Expected 'gemini' or 'ollama'."
    )


def initialize_llm(*, force: bool = False) -> None:
    global _llm_client
    if _llm_client is None or force:
        _llm_client = build_llm_client()


def get_llm_client() -> LLMClient:
    global _llm_client
    if _llm_client is None:
        initialize_llm()
    return _llm_client


def reset_llm_client() -> None:
    global _llm_client
    _llm_client = None
